title: "Swift for all - by Arthur Rodrigues"
description: "iOS Developer – Swift • SwiftUI • MVVM"
url: "https://arthursmr.github.io"
baseurl: ""
lang: "en-US"

author:
  name: "Arthur Rodrigues"
  email: "arthursmr17@gmail.com"
  url: "https://arthursmr.github.io"

theme: minimal-mistakes-jekyll

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Navigation menu items
nav:
  - title: "Home"
    url: /
  - title: "Projects"
    url: /projects/
  - title: "Blog"
    url: /blog/
  - title: "About"
    url: /about/

# Social links (icons aparecem automaticamente)
social:
  github: "ArthurSMR"
  twitter: "thui_dev"
  linkedin: "arthursmr17"

# Dark mode ativado
minimal_mistakes_skin: "dark"

# Outras opções do tema
exclude:
  - README.md
