title: "Swift for all - by Arthur Rodrigues"
description: "iOS Developer – Swift • SwiftUI • MVVM"
url: "https://arthursmr.github.io"
baseurl: ""
lang: "en-US"

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

minima:
  hide_site_feed_link: true
  nav_pages:
    - projects.md
    - blog.md
    - about.md

github_username: ArthurSMR
linkedin_username: arthursmr17
