title: "Swift for all - by Arthur Rodrigues"
description: "iOS Developer – Swift • SwiftUI • MVVM"
url: "https://arthursmr.github.io"
baseurl: ""
lang: "en"

author:
  name: "Arthur Rodrigues"
  email: "arthursmr17@gmail.com"

theme: minima

plugins:
  - jekyll-feed

github_username: ArthurSMR
twitter_username: thui_dev
linkedin_username: arthursmr17

minima:
  nav_pages:
    - index.md
    - projects.md
    - blog.md
    - about.md

  hide_site_feed_link: true