title: "Swift for all - by Arthur Rodrigues"
email: arthursmr17@gmail.com
description: "iOS Developer – Swift • SwiftUI • MVVM"
baseurl: "" # leave empty for a user site (username.github.io)
url: "https://arthursmr.github.io"
# theme: minima
plugins:
  - jekyll-feed
github_username: ArthurSMR