title: "Arthur Rodrigues – iOS Developer"
email: your.email@example.com
description: "iOS Developer – Swift • SwiftUI • MVVM • Based in Malta"
baseurl: "" # leave empty for a user site (username.github.io)
url: "https://arthursmr.github.io"
theme: minima
plugins:
  - jekyll-feed
github_username: ArthurSMR