title: "Swift for all - by Arthur Rodrigues"
description: "iOS Developer – Swift • SwiftUI • MVVM"
url: "https://arthursmr.github.io"
baseurl: ""
lang: "en-US"

author:
  name: "Arthur Rodrigues"
  email: "arthursmr17@gmail.com"
  url: "https://arthursmr.github.io"

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Navigation menu items
minima:
  nav_pages:
    - index.md
    - projects.md
    - blog.md
    - about.md

# Social links (icons aparecem automaticamente)
github_username: ArthurSMR
twitter_username: thui_dev
linkedin_username: arthursmr17