window.TEXLASER_LOCALES = window.TEXLASER_LOCALES || {};
window.TEXLASER_LOCALES.en = {
  meta: { title: 'Texlaser Group — industrial technology applied to results', description: 'Texlaser Group — industrial laser and ozone technology solutions for more precise, efficient processes.' }, brand: { home: 'Texlaser Group — home' }, nav: { menu: 'Menu', label: 'Main navigation', solutions: 'Solutions', machines: 'Machines', applications: 'Applications', process: 'How we work', founder: 'Founder', company: 'Company' }, language: { label: 'Language' }, common: { talkToUs: 'Talk to an advisor <span>↗</span>', scroll: 'SCROLL <span></span>' },
  hero: { imageAlt: 'Technical environment for industrial technology', eyebrow: '<span class="eyebrow-line"></span> BRAZIL · SP', title: 'Technology that<br /><em>moves</em> production.', copy: 'Industrial laser and ozone solutions that turn processes into greater precision, productivity, and results.', explore: 'Explore solutions <span>↓</span>', note: '<span class="pulse-dot"></span> Technology for Brazilian industry' },
  company: { label: '<span>01</span> THE GROUP', kicker: 'Two fronts. One process vision.', title: 'Applied engineering for those who need to <span>produce better.</span>', copy: 'Texlaser Group distributes industrial technology for companies that cannot stop. We bring laser and ozone solutions together with a practical view of operation, implementation, and results.', cta: 'Talk to our team <span>↗</span>', aside: 'Direct service in São Paulo, focused on real applications and long-term relationships.' },
  founder: { imageAlt: 'Alex Rodrigues, founder of Texlaser Group', caption: 'ALEX RODRIGUES · FOUNDER', label: '<span>02</span> WHO LEADS THE WAY', kicker: 'Experience that understands operations from the inside.', title: 'Before distributing technology, <span>Alex lived production.</span>', copy1: 'With more than 20 years in the industrial laser market, Alex Rodrigues combines technical knowledge, training, and hands-on experience to guide every decision with greater clarity.', copy2: 'He has led trade shows and industry training, and also ran an industrial denim laundry — seeing up close the challenges, pace, and demands of production.', route: 'A journey across markets', routeDetail: 'From Pernambuco to Rio Grande do Sul, with experience beyond Brazil as well.' },
  solutions: { label: '<span>03</span> OUR FOCUSES', lead: 'The right technology for the right process. We start with denim and industrial laundries.', laser: { type: 'LASER MACHINES', copy: 'Finishing, marking, and customization with more control, repeatability, and creative freedom for denim, T-shirts, and fabrics.' }, ozone: { type: 'OZONE GENERATORS', copy: 'Ozone generators for industrial applications in laundries, water and wastewater treatment, food, and other processes.' } }, tags: { denim: 'JEANS / DENIM', apparel: 'APPAREL', fabric: 'FABRIC', laundries: 'LAUNDRIES', water: 'WATER / WASTEWATER', industrial: 'INDUSTRIAL PROCESSES' },
  products: { label: '<span>04</span> EQUIPMENT', kicker: 'A look inside the process', title: 'Machines that enter<br /><em>the operation.</em>', lead: 'Scroll to explore each solution, its applications, and key technical data.', laserAlt: 'Industrial laser machine for denim and fabrics', ozoneAlt: 'Ozoclean ozone generator in an industrial environment', laser: { kicker: 'Texlaser · textile finishing', title: 'Precision to<br /><em>create scale.</em>', copy: 'CO₂ laser for denim, T-shirts, and fabrics. A platform to create effects, mark surfaces, and bring greater consistency to finishing.', note: 'Preliminary data · confirm commercial configuration.' }, ozone: { kicker: 'Ozoclean · industrial treatment', title: 'Cleaner, more<br /><em>controlled processes.</em>', copy: 'Ozone generators for laundries, water and wastewater, and other industrial applications that require control, efficiency, and operational safety.', note: 'Specifications and scope depend on the project.' } }, specs: { power: 'Power', workArea: 'Work area', dimensions: 'Dimensions', cooling: 'Cooling', waterChiller: 'Water · chiller', applications: 'Applications', industrialLaundries: 'Industrial laundries', processes: 'Processes', waterWaste: 'Water and wastewater', installation: 'Installation', projectByApplication: 'Project-specific', service: 'Service', saoPaulo: 'Brazil · São Paulo' },
  applications: { label: '<span>05</span> WHERE WE APPLY', title: 'From the laundry<br />to the production line.', copy: 'A technology base that follows your process needs — today and at the next stage.', item1: 'Industrial denim laundries', item2: 'Apparel and textile finishing', item3: 'Water and wastewater treatment', item4: 'Other industrial applications' }, process: { label: '<span>06</span> HOW WE WORK', title: 'Equipment is the beginning.<br /><span>Results are the goal.</span>', step1: { title: 'Understand', copy: 'We discuss your process, volume, and challenge.' }, step2: { title: 'Specify', copy: 'We find the configuration that makes sense for the operation.' }, step3: { title: 'Implement', copy: 'We support the technology’s entry into the factory routine.' }, step4: { title: 'Support', copy: 'Training and support to keep production moving forward.' } }, contact: { label: '<span>07</span> LET’S TALK', title: 'The next step starts with a <em>good conversation.</em>', copy: 'Tell us about your operation. Our advisor will direct you to the best solution.' }, form: { name: 'Your name', namePlaceholder: 'What should we call you?', company: 'Company', companyPlaceholder: 'Company name', message: 'How can we help?', messagePlaceholder: 'Tell us briefly about your operation', note: 'Official sales channel being configured.', success: 'Message recorded in this demo.' }, footer: { tagline: 'Precision for the process.<br />Presence for the result.', copyright: '© 2026 Texlaser Group', location: 'Direct service in São Paulo · Brazil', status: 'Site in development' }
};
window.TEXLASER_LOCALES.en.language.select = 'Select language';
window.TEXLASER_LOCALES.en.company.tag = 'TX / 01 — BRAZIL';
window.TEXLASER_LOCALES.en.founder.markets = 'Brazil · Argentina · Spain';
window.TEXLASER_LOCALES.en.products.laserStage = 'TEXLASER / CO₂';
window.TEXLASER_LOCALES.en.products.ozoneStage = 'OZOCLEAN / O₃';
