window.TEXLASER_LOCALES = window.TEXLASER_LOCALES || {};
window.TEXLASER_LOCALES.en = {
  meta: { title: 'Texlaser Group — industrial technology applied to results', description: 'Texlaser Group — industrial laser and ozone technology solutions for more precise, efficient processes.' }, brand: { home: 'Texlaser Group — home' }, nav: { menu: 'Menu', label: 'Main navigation', solutions: 'Solutions', machines: 'Machines', applications: 'Applications', process: 'How we work', founder: 'Founder', company: 'Company' }, language: { label: 'Language' }, common: { talkToUs: 'Talk to an advisor <span>↗</span>', scroll: 'SCROLL <span></span>' },
  hero: { imageAlt: 'Industrial laser machine in a production environment', eyebrow: '', title: 'Laser &amp; ozone<br /><em>industrial.</em>', copy: 'Machines, implementation, and support.', explore: 'See the machines <span>↓</span>', laserLabel: 'Textile laser', laserDetail: 'Finishing and customization', ozoneLabel: 'Ozone generators', ozoneDetail: 'Industrial treatment' },
  machineFocus: { label: '<span>02</span> TECHNOLOGIES', title: 'Two technologies for the real operation.', lead: 'Two industrial fronts for different stages of your operation.', laserLabel: 'TEXLASER', laserTitle: 'CO₂ laser', laserCopy: 'Textile finishing, marking, and customization.', laserAction: 'See the laser machine <span>↗</span>', ozoneLabel: 'OZOCLEAN', ozoneTitle: 'Ozone generators', ozoneCopy: 'Industrial treatment with more control.', ozoneAction: 'See ozone generators <span>↗</span>' },
  company: { label: '<span>01</span> THE GROUP', kicker: '', title: 'Technology for the <span>real operation.</span>', copy: 'Laser and ozone with implementation, training, and support for companies that need to produce.', cta: 'Talk to our team <span>↗</span>', aside: '', visualCaption: 'OZOCLEAN / O₃' },
  founder: { imageAlt: 'Alex Rodrigues, founder of Texlaser Group', caption: 'ALEX RODRIGUES · FOUNDER', label: '<span>06</span> WHO LEADS THE WAY', kicker: 'Experience that understands operations from the inside.', title: 'Alex understands <span>production from within.</span>', copy1: 'More than 20 years in industrial laser, with experience in training, trade shows, and a denim laundry.', copy2: 'He has led industry training and lived the demands of production up close.', route: 'PROFESSIONAL JOURNEY', markets: 'Brazil · Argentina · Spain', routeDetail: 'From Brazil’s Northeast to the South, with experience beyond the country.' },
  solutions: { label: '<span>02</span> OUR FOCUSES', lead: 'The right technology for the right process. We start with denim and industrial laundries.', laser: { type: 'LASER MACHINES', copy: 'Finishing, marking, and customization with more control, repeatability, and creative freedom for denim, T-shirts, and fabrics.' }, ozone: { type: 'OZONE GENERATORS', copy: 'Ozone generators for industrial applications in laundries, water and wastewater treatment, food, and other processes.' } }, tags: { denim: 'JEANS / DENIM', apparel: 'APPAREL', fabric: 'FABRIC', laundries: 'LAUNDRIES', water: 'WATER / WASTEWATER', industrial: 'INDUSTRIAL PROCESSES' },
  products: { label: '<span>03</span> EQUIPMENT', kicker: '', title: 'Machines for the<br /><em>operation.</em>', lead: '', laserAlt: 'Industrial laser machine for denim and fabrics', ozoneAlt: 'Ozoclean ozone generator in an industrial environment', laser: { kicker: 'Texlaser · textile finishing', title: 'Precision to<br /><em>create scale.</em>', copy: 'CO₂ laser for denim, T-shirts, and fabrics. A platform to create effects, mark surfaces, and bring greater consistency to finishing.', note: 'Preliminary data · confirm commercial configuration.' }, ozone: { kicker: 'Ozoclean · industrial treatment', title: 'Cleaner, more<br /><em>controlled processes.</em>', copy: 'Ozone generators for laundries, water and wastewater, and other industrial applications that require control, efficiency, and operational safety.', note: 'Specifications and scope depend on the project.' } }, specs: { power: 'Power', workArea: 'Work area', dimensions: 'Dimensions', cooling: 'Cooling', waterChiller: 'Water · chiller', applications: 'Applications', industrialLaundries: 'Industrial laundries', processes: 'Processes', waterWaste: 'Water and wastewater', installation: 'Project-specific', service: 'Service', saoPaulo: 'Brazil · São Paulo' },
  applications: { label: '<span>04</span> WHERE WE APPLY', title: 'From the laundry<br />to the production line.', copy: 'A technology base that follows your process needs — today and at the next stage.', item1: 'Industrial denim laundries', item2: 'Apparel and textile finishing', item3: 'Water and wastewater treatment', item4: 'Other industrial applications' }, process: { label: '<span>05</span> HOW WE WORK', title: 'Equipment is the beginning.<br /><span>Results are the goal.</span>', step1: { title: 'Understand', copy: 'We discuss your process, volume, and challenge.' }, step2: { title: 'Specify', copy: 'We find the configuration that makes sense for the operation.' }, step3: { title: 'Implement', copy: 'We support the technology’s entry into the factory routine.' }, step4: { title: 'Support', copy: 'Training and support to keep production moving forward.' } }, contact: { label: '<span>07</span> LET’S TALK', title: 'The next step starts with a <em>good conversation.</em>', copy: 'Tell us about your operation. Our advisor will direct you to the best solution.' }, form: { name: 'Your name', namePlaceholder: 'What should we call you?', company: 'Company', companyPlaceholder: 'Company name', message: 'How can we help?', messagePlaceholder: 'Tell us briefly about your operation', note: 'Official sales channel being configured.', success: 'Message recorded in this demo.' }, footer: { tagline: 'Precision for the process.<br />Presence for the result.', copyright: '© 2026 Texlaser Group', location: 'Direct service in São Paulo · Brazil', status: 'Site in development' }
};
window.TEXLASER_LOCALES.en.language.select = 'Select language';
window.TEXLASER_LOCALES.en.company.tag = 'TX / 01 — BRAZIL';
window.TEXLASER_LOCALES.en.founder.markets = 'Brazil · Argentina · Spain';
window.TEXLASER_LOCALES.en.products.laserStage = 'TEXLASER / CO₂';
window.TEXLASER_LOCALES.en.products.ozoneStage = 'OZOCLEAN / O₃';
