window.TEXLASER_LOCALES = window.TEXLASER_LOCALES || {};
window.TEXLASER_LOCALES.en = {
  meta: { title: 'Texlaser Group — industrial technology applied to results', description: 'Texlaser Group — industrial laser and ozone technology solutions for more precise, efficient processes.' }, brand: { home: 'Texlaser Group — home' }, nav: { menu: 'Menu', label: 'Main navigation', solutions: 'Solutions', machines: 'Machines', applications: 'Applications', process: 'How we work', founder: 'Our story', company: 'Company' }, language: { label: 'Language' }, common: { talkToUs: 'Talk to our team <span>↗</span>', scroll: 'SCROLL <span></span>' },
  hero: { imageAlt: 'Laser machines and ozone generators for industrial processes', kicker: 'TEXTILE LASER · INDUSTRIAL OZONE', eyebrow: '', title: 'Textile laser.<br /><em>Industrial ozone.</em>', copy: 'Equipment with installation, training, and technical support.', explore: 'See the machines <span>↓</span>', laserLabel: 'Textile laser', laserDetail: 'Finishing and customization', ozoneLabel: 'Ozone generators', ozoneDetail: 'Industrial treatment' },
  machineFocus: { ariaLabel: 'Texlaser Group technologies', label: '<span>01</span> TECHNOLOGIES', title: 'Laser and ozone for your operation.', lead: 'Two industrial technologies, with installation and technical support.', laserLabel: 'TEXLASER', laserTitle: 'CO₂ laser', laserCopy: 'Textile finishing, marking, and customization.', laserAction: 'See the laser machine <span>↗</span>', ozoneLabel: 'OZOCLEAN', ozoneTitle: 'Ozone generators', ozoneCopy: 'Industrial treatment with more control.', ozoneAction: 'See ozone generators <span>↗</span>' },
  company: { label: '<span>01</span> THE GROUP', kicker: '', title: 'From equipment<br /><span>to operation.</span>', copy: 'Industrial technology distribution with implementation, training, and support in São Paulo.', cta: 'Talk to our team <span>↗</span>', aside: '', visualCaption: 'OZOCLEAN / O₃' },
  founder: { imageAlt: 'Alex Rodrigues, founder of Texlaser Group', caption: 'ALEX RODRIGUES · FOUNDER', label: '<span>05</span> WHO LEADS THE WAY', kicker: '', title: '20 years between <span>technology and production.</span>', copy1: 'Alex Rodrigues has worked in industrial laser for over 20 years, through training, trade shows, and industry projects.', copy2: 'Having led a denim laundry, he knows the factory floor and its challenges firsthand.', route: 'FIELD EXPERIENCE', markets: 'Experience across industrial regions.', routeDetail: 'Work throughout Brazil and on international projects.' },
  solutions: { label: '<span>02</span> OUR FOCUSES', lead: 'The right technology for the right process. We start with denim and industrial laundries.', laser: { type: 'LASER MACHINES', copy: 'Finishing, marking, and customization with more control, repeatability, and creative freedom for denim, T-shirts, and fabrics.' }, ozone: { type: 'OZONE GENERATORS', copy: 'Ozone generators for industrial applications in laundries, water and wastewater treatment, food, and other processes.' } }, tags: { denim: 'JEANS / DENIM', apparel: 'APPAREL', fabric: 'FABRIC', laundries: 'LAUNDRIES', water: 'WATER / WASTEWATER', industrial: 'INDUSTRIAL PROCESSES' },
  products: { label: '<span>02</span> EQUIPMENT', kicker: '', title: 'Inside each<br /><em>machine.</em>', lead: '', laserAlt: 'Industrial laser machine for denim and fabrics', ozoneAlt: 'Ozoclean ozone generator in an industrial environment', laser: { kicker: 'Texlaser · textile finishing', title: 'Precision to<br /><em>create scale.</em>', copy: 'CO₂ laser for denim, T-shirts, and fabrics. A platform to create effects, mark surfaces, and bring greater consistency to finishing.', note: 'Preliminary data · confirm commercial configuration.' }, ozone: { kicker: 'Ozoclean · industrial treatment', title: 'Ozone built<br /><em>into the process.</em>', copy: 'Ozone generators for laundries, water and wastewater, and other industrial applications that require control, efficiency, and operational safety.', note: 'Specifications and scope depend on the project.' } }, specs: { power: 'Power', workArea: 'Work area', dimensions: 'Dimensions', cooling: 'Cooling', waterChiller: 'Water · chiller', applications: 'Applications', industrialLaundries: 'Industrial laundries', processes: 'Processes', waterWaste: 'Water and wastewater', installation: 'Project-specific', service: 'Service', saoPaulo: 'Brazil · São Paulo' },
  applications: { label: '<span>03</span> APPLICATIONS', title: 'Technology for<br />industry.', copy: 'Solutions for different stages of production.', item1: 'Industrial denim laundries', item2: 'Apparel and textile finishing', item3: 'Water and wastewater treatment', item4: 'Other industrial applications' }, process: { label: '<span>04</span> HOW WE WORK', title: 'From conversation<br /><span>to operation.</span>', step1: { title: 'Understand', copy: 'We learn about your process and needs.' }, step2: { title: 'Specify', copy: 'We define the right configuration.' }, step3: { title: 'Implement', copy: 'We support installation into your operation.' }, step4: { title: 'Support', copy: 'Training and technical support.' } }, contact: { label: '<span>06</span> LET’S TALK', title: 'Let’s talk about your <em>operation.</em>', copy: 'Talk with our team about textile laser or industrial ozone.' }, form: { name: 'Your name', namePlaceholder: 'What should we call you?', company: 'Company', companyPlaceholder: 'Company name', message: 'How can we help?', messagePlaceholder: 'Tell us briefly about your operation', note: 'Sending is not connected yet. This form does not deliver messages.', success: 'Message not sent: this form is still being configured.' }, footer: { tagline: 'Precision for the process.<br />Presence for the result.', copyright: '© 2026 Texlaser Group', location: 'Service in São Paulo · Brazil', status: 'Site in development' }
};
window.TEXLASER_LOCALES.en.language.select = 'Select language';
window.TEXLASER_LOCALES.en.company.tag = 'TX / 01 — BRAZIL';
window.TEXLASER_LOCALES.en.founder.markets = 'Experience in Brazil and abroad.';
window.TEXLASER_LOCALES.en.products.laserStage = 'TEXLASER / CO₂';
window.TEXLASER_LOCALES.en.products.ozoneStage = 'OZOCLEAN / O₃';
