window.TEXLASER_LOCALES = window.TEXLASER_LOCALES || {};
window.TEXLASER_LOCALES.es = {
  meta:{title:'Texlaser Group — tecnología industrial aplicada al resultado',description:'Texlaser Group — soluciones industriales en tecnología láser y ozono para procesos más precisos y eficientes.'},brand:{home:'Texlaser Group — inicio'},nav:{menu:'Menú',label:'Navegación principal',solutions:'Soluciones',machines:'Máquinas',applications:'Aplicaciones',process:'Cómo trabajamos',founder:'Fundador',company:'Empresa'},language:{label:'Idioma'},common:{talkToUs:'Hablar con un asesor <span>↗</span>',scroll:'DESPLAZAR <span></span>'},
  hero:{imageAlt:'Entorno técnico para tecnología industrial',eyebrow:'<span class="eyebrow-line"></span> BRASIL · SP',title:'Tecnología que<br /><em>mueve</em> la producción.',copy:'Soluciones industriales de láser y ozono para convertir los procesos en más precisión, productividad y resultados.',explore:'Conocer soluciones <span>↓</span>',note:'<span class="pulse-dot"></span> Tecnología para la industria brasileña'},
  company:{label:'<span>01</span> EL GRUPO',kicker:'Dos frentes. Una visión de proceso.',title:'Ingeniería aplicada para quienes necesitan <span>producir mejor.</span>',copy:'Texlaser Group distribuye tecnología industrial para empresas que no pueden parar. Unimos soluciones láser y ozono con una visión práctica de operación, implementación y resultados.',cta:'Habla con nuestro equipo <span>↗</span>',aside:'Atención directa en São Paulo, centrada en aplicaciones reales y relaciones a largo plazo.'},
  founder:{imageAlt:'Alex Rodrigues, fundador de Texlaser Group',caption:'ALEX RODRIGUES · FUNDADOR',label:'<span>06</span> QUIÉN ESTÁ AL FRENTE',kicker:'Experiencia que conoce la operación desde dentro.',title:'Alex conoce la <span>producción desde dentro.</span>',copy1:'Más de 20 años en el láser industrial, con experiencia en formación, ferias y una lavandería de denim.',copy2:'También ha vivido de cerca las exigencias de la producción.',route:'TRAYECTORIA PROFESIONAL',markets:'Brasil · Argentina · España',routeDetail:'Del Nordeste al Sur de Brasil, con experiencia también fuera del país.'},
  solutions:{label:'<span>02</span> NUESTROS FRENTES',lead:'La tecnología adecuada para el proceso adecuado. Empezamos con el denim y las lavanderías industriales.',laser:{type:'MÁQUINAS LÁSER',copy:'Acabado, marcado y personalización con más control, repetibilidad y libertad creativa para denim, camisetas y tejidos.'},ozone:{type:'GENERADORES DE OZONO',copy:'Generadores de ozono para aplicaciones industriales en lavanderías, tratamiento de agua y efluentes, alimentos y otros procesos.'}},tags:{denim:'JEANS / DENIM',apparel:'CONFECCIÓN',fabric:'TEJIDO',laundries:'LAVANDERÍAS',water:'AGUA / EFLUENTES',industrial:'PROCESOS INDUSTRIALES'},
  products:{label:'<span>03</span> EQUIPOS',kicker:'Una mirada al interior del proceso',title:'Máquinas que entran<br /><em>en la operación.</em>',lead:'Desplázate para explorar cada solución, sus aplicaciones y los principales datos técnicos.',laserAlt:'Máquina láser industrial para denim y tejidos',ozoneAlt:'Generador de ozono Ozoclean en un entorno industrial',laser:{kicker:'Texlaser · acabado textil',title:'Precisión para<br /><em>crear escala.</em>',copy:'Láser CO₂ para denim, camisetas y tejidos. Una plataforma para crear efectos, marcar superficies y aportar más consistencia al acabado.',note:'Datos preliminares · confirmar configuración comercial.'},ozone:{kicker:'Ozoclean · tratamiento industrial',title:'Procesos más<br /><em>limpios y controlados.</em>',copy:'Generadores de ozono para lavanderías, agua y efluentes y otras aplicaciones industriales que requieren control, eficiencia y seguridad operativa.',note:'Especificaciones y alcance según el proyecto.'}},specs:{power:'Potencia',workArea:'Área de trabajo',dimensions:'Dimensiones',cooling:'Refrigeración',waterChiller:'Agua · chiller',applications:'Aplicaciones',industrialLaundries:'Lavanderías industriales',processes:'Procesos',waterWaste:'Agua y efluentes',installation:'Instalación',projectByApplication:'Proyecto por aplicación',service:'Atención',saoPaulo:'Brasil · São Paulo'},
  applications:{label:'<span>04</span> DÓNDE APLICAMOS',title:'De la lavandería<br />a la línea de producción.',copy:'Una base tecnológica que acompaña las necesidades de tu proceso — hoy y en la próxima etapa.',item1:'Lavanderías industriales de denim',item2:'Confecciones y acabado textil',item3:'Tratamiento de agua y efluentes',item4:'Otras aplicaciones industriales'},process:{label:'<span>05</span> CÓMO TRABAJAMOS',title:'El equipo es el comienzo.<br /><span>El resultado es el objetivo.</span>',step1:{title:'Entender',copy:'Hablamos sobre tu proceso, volumen y desafío.'},step2:{title:'Especificar',copy:'Encontramos la configuración adecuada para la operación.'},step3:{title:'Implementar',copy:'Apoyamos la incorporación de la tecnología a la fábrica.'},step4:{title:'Acompañar',copy:'Formación y soporte para mantener la producción avanzando.'}},contact:{label:'<span>07</span> HABLEMOS',title:'El siguiente paso comienza con una <em>buena conversación.</em>',copy:'Cuéntanos sobre tu operación. Nuestro asesor te dirigirá a la mejor solución.'},form:{name:'Tu nombre',namePlaceholder:'¿Cómo podemos llamarte?',company:'Empresa',companyPlaceholder:'Nombre de la empresa',message:'¿Cómo podemos ayudarte?',messagePlaceholder:'Cuéntanos brevemente sobre tu operación',note:'Canal comercial oficial en configuración.',success:'Mensaje registrado en esta demostración.'},footer:{tagline:'Precisión para el proceso.<br />Presencia para el resultado.',copyright:'© 2026 Texlaser Group',location:'Atención directa en São Paulo · Brasil',status:'Sitio en desarrollo'}
};
window.TEXLASER_LOCALES.es.language.select = 'Seleccionar idioma';
window.TEXLASER_LOCALES.es.company.tag = 'TX / 01 — BRASIL';
window.TEXLASER_LOCALES.es.founder.markets = 'Brasil · Argentina · España';
window.TEXLASER_LOCALES.es.products.laserStage = 'TEXLASER / CO₂';
window.TEXLASER_LOCALES.es.products.ozoneStage = 'OZOCLEAN / O₃';
