window.TEXLASER_LOCALES = window.TEXLASER_LOCALES || {};
window.TEXLASER_LOCALES.es = {
  meta:{title:'Texlaser Group — tecnología industrial aplicada al resultado',description:'Texlaser Group — soluciones industriales en tecnología láser y ozono para procesos más precisos y eficientes.'},brand:{home:'Texlaser Group — inicio'},nav:{menu:'Menú',label:'Navegación principal',solutions:'Soluciones',machines:'Máquinas',applications:'Aplicaciones',process:'Cómo trabajamos',founder:'Fundador',company:'Empresa'},language:{label:'Idioma'},common:{talkToUs:'Hablar con nuestro equipo <span>↗</span>',scroll:'DESPLAZAR <span></span>'},
  hero:{imageAlt:'Máquinas láser y generadores de ozono para procesos industriales',kicker:'MÁQUINAS LÁSER · GENERADORES DE OZONO',eyebrow:'',title:'Tecnología que<br /><em>transforma la producción.</em>',copy:'Implementación, formación y soporte técnico.',explore:'Ver las máquinas <span>↓</span>',laserLabel:'Láser textil',laserDetail:'Acabado y personalización',ozoneLabel:'Generadores de ozono',ozoneDetail:'Tratamiento industrial'},
  machineFocus:{label:'<span>02</span> TECNOLOGÍAS',title:'Dos tecnologías para la operación real.',lead:'Dos frentes industriales para diferentes momentos de la operación.',laserLabel:'TEXLASER',laserTitle:'Láser CO₂',laserCopy:'Acabado, marcado y personalización textil.',laserAction:'Ver máquina láser <span>↗</span>',ozoneLabel:'OZOCLEAN',ozoneTitle:'Generadores de ozono',ozoneCopy:'Tratamiento industrial con más control.',ozoneAction:'Ver generadores de ozono <span>↗</span>'},
  company:{label:'<span>01</span> EL GRUPO',kicker:'',title:'Del equipo<br /><span>a la operación.</span>',copy:'Distribución de tecnología industrial con implementación, formación y soporte en São Paulo.',cta:'Habla con nuestro equipo <span>↗</span>',aside:'',visualCaption:'OZOCLEAN / O₃'},
  founder:{imageAlt:'Alex Rodrigues, fundador de Texlaser Group',caption:'ALEX RODRIGUES · FUNDADOR',label:'<span>06</span> QUIÉN ESTÁ AL FRENTE',kicker:'',title:'20 años entre <span>tecnología y producción.</span>',copy1:'Alex Rodrigues trabaja desde hace más de 20 años con láser industrial, formación, ferias y proyectos del sector.',copy2:'Al frente de una lavandería de denim, conoció de cerca la rutina y los desafíos de la fábrica.',route:'EXPERIENCIA EN CAMPO',markets:'Experiencia en Brasil y en el exterior.',routeDetail:'Actuación en polos industriales de Brasil, Argentina y España.'},
  solutions:{label:'<span>02</span> NUESTROS FRENTES',lead:'La tecnología adecuada para el proceso adecuado. Empezamos con el denim y las lavanderías industriales.',laser:{type:'MÁQUINAS LÁSER',copy:'Acabado, marcado y personalización con más control, repetibilidad y libertad creativa para denim, camisetas y tejidos.'},ozone:{type:'GENERADORES DE OZONO',copy:'Generadores de ozono para aplicaciones industriales en lavanderías, tratamiento de agua y efluentes, alimentos y otros procesos.'}},tags:{denim:'JEANS / DENIM',apparel:'CONFECCIÓN',fabric:'TEJIDO',laundries:'LAVANDERÍAS',water:'AGUA / EFLUENTES',industrial:'PROCESOS INDUSTRIALES'},
  products:{label:'<span>03</span> EQUIPOS',kicker:'',title:'Máquinas para la<br /><em>operación.</em>',lead:'',laserAlt:'Máquina láser industrial para denim y tejidos',ozoneAlt:'Generador de ozono Ozoclean en un entorno industrial',laser:{kicker:'Texlaser · acabado textil',title:'Precisión para<br /><em>crear escala.</em>',copy:'Láser CO₂ para denim, camisetas y tejidos. Una plataforma para crear efectos, marcar superficies y aportar más consistencia al acabado.',note:'Datos preliminares · confirmar configuración comercial.'},ozone:{kicker:'Ozoclean · tratamiento industrial',title:'Procesos más<br /><em>limpios y controlados.</em>',copy:'Generadores de ozono para lavanderías, agua y efluentes y otras aplicaciones industriales que requieren control, eficiencia y seguridad operativa.',note:'Especificaciones y alcance según el proyecto.'}},specs:{power:'Potencia',workArea:'Área de trabajo',dimensions:'Dimensiones',cooling:'Refrigeración',waterChiller:'Agua · chiller',applications:'Aplicaciones',industrialLaundries:'Lavanderías industriales',processes:'Procesos',waterWaste:'Agua y efluentes',installation:'Instalación',projectByApplication:'Proyecto por aplicación',service:'Atención',saoPaulo:'Brasil · São Paulo'},
  applications:{label:'<span>04</span> DÓNDE APLICAMOS',title:'De la lavandería<br />a la línea de producción.',copy:'Una base tecnológica que acompaña las necesidades de tu proceso — hoy y en la próxima etapa.',item1:'Lavanderías industriales de denim',item2:'Confecciones y acabado textil',item3:'Tratamiento de agua y efluentes',item4:'Otras aplicaciones industriales'},process:{label:'<span>05</span> CÓMO TRABAJAMOS',title:'El equipo es el comienzo.<br /><span>El resultado es el objetivo.</span>',step1:{title:'Entender',copy:'Hablamos sobre tu proceso, volumen y desafío.'},step2:{title:'Especificar',copy:'Encontramos la configuración adecuada para la operación.'},step3:{title:'Implementar',copy:'Apoyamos la incorporación de la tecnología a la fábrica.'},step4:{title:'Acompañar',copy:'Formación y soporte para mantener la producción avanzando.'}},contact:{label:'<span>07</span> HABLEMOS',title:'El siguiente paso comienza con una <em>buena conversación.</em>',copy:'Cuéntanos sobre tu operación. Nuestro asesor te dirigirá a la mejor solución.'},form:{name:'Tu nombre',namePlaceholder:'¿Cómo podemos llamarte?',company:'Empresa',companyPlaceholder:'Nombre de la empresa',message:'¿Cómo podemos ayudarte?',messagePlaceholder:'Cuéntanos brevemente sobre tu operación',note:'Canal comercial oficial en configuración.',success:'Mensaje registrado en esta demostración.'},footer:{tagline:'Precisión para el proceso.<br />Presencia para el resultado.',copyright:'© 2026 Texlaser Group',location:'Atención directa en São Paulo · Brasil',status:'Sitio en desarrollo'}
};
window.TEXLASER_LOCALES.es.language.select = 'Seleccionar idioma';
window.TEXLASER_LOCALES.es.company.tag = 'TX / 01 — BRASIL';
window.TEXLASER_LOCALES.es.founder.markets = 'Experiencia en Brasil y en el exterior.';
window.TEXLASER_LOCALES.es.products.laserStage = 'TEXLASER / CO₂';
window.TEXLASER_LOCALES.es.products.ozoneStage = 'OZOCLEAN / O₃';
