window.TEXLASER_LOCALES = window.TEXLASER_LOCALES || {};
window.TEXLASER_LOCALES['pt-BR'] = {
  meta: { title: 'Texlaser Group — tecnologia industrial aplicada ao resultado', description: 'Texlaser Group — soluções industriais em tecnologia laser e ozônio para processos mais precisos e eficientes.' },
  brand: { home: 'Texlaser Group — início' }, nav: { menu: 'Menu', label: 'Navegação principal', solutions: 'Soluções', machines: 'Máquinas', applications: 'Aplicações', process: 'Como trabalhamos', founder: 'Fundador', company: 'Empresa' }, language: { label: 'Idioma' }, common: { talkToUs: 'Falar com nossa equipe <span>↗</span>', scroll: 'SCROLL <span></span>' },
  hero: { imageAlt: 'Máquinas laser e geradores de ozônio para processos industriais', kicker: 'MÁQUINAS LASER · GERADORES DE OZÔNIO', eyebrow: '', title: 'Tecnologia que<br /><em>transforma a produção.</em>', copy: 'Implantação, treinamento e suporte técnico.', explore: 'Ver as máquinas <span>↓</span>', laserLabel: 'Laser têxtil', laserDetail: 'Acabamento e personalização', ozoneLabel: 'Geradores de ozônio', ozoneDetail: 'Tratamento industrial' },
  machineFocus: { label: '<span>02</span> TECNOLOGIAS', title: 'Duas tecnologias para a operação real.', lead: 'Duas frentes industriais para diferentes momentos da operação.', laserLabel: 'TEXLASER', laserTitle: 'Laser CO₂', laserCopy: 'Acabamento, marcação e personalização têxtil.', laserAction: 'Ver máquina laser <span>↗</span>', ozoneLabel: 'OZOCLEAN', ozoneTitle: 'Geradores de ozônio', ozoneCopy: 'Tratamento industrial com mais controle.', ozoneAction: 'Ver geradores de ozônio <span>↗</span>' },
  company: { label: '<span>01</span> O GRUPO', kicker: '', title: 'Do equipamento<br /><span>à operação.</span>', copy: 'Distribuição de tecnologia industrial com implantação, treinamento e suporte em São Paulo.', cta: 'Falar com a equipe <span>↗</span>', aside: '', visualCaption: 'OZOCLEAN / O₃' },
  founder: { imageAlt: 'Alex Rodrigues, fundador da Texlaser Group', caption: 'ALEX RODRIGUES · FUNDADOR', label: '<span>06</span> QUEM ESTÁ À FRENTE', kicker: '', title: '20 anos entre <span>tecnologia e produção.</span>', copy1: 'Alex Rodrigues atua há mais de 20 anos no laser industrial, com presença em treinamentos, feiras e projetos do setor.', copy2: 'À frente de uma lavanderia de jeans, conheceu de perto a rotina e os desafios do chão de fábrica.', route: 'PRESENÇA EM CAMPO', markets: 'Experiência no Brasil e no exterior.', routeDetail: 'Atuação em polos industriais brasileiros, Argentina e Espanha.' },
  solutions: { label: '<span>02</span> NOSSAS FRENTES', lead: 'Tecnologia certa para o processo certo. Começamos pelo universo do jeans e das lavanderias industriais.', laser: { type: 'MÁQUINAS LASER', copy: 'Acabamento, marcação e personalização com mais controle, repetibilidade e liberdade criativa para jeans, camisetas e tecidos.' }, ozone: { type: 'GERADORES DE OZÔNIO', copy: 'Geradores de ozônio para aplicações industriais em lavanderias, tratamento de água e efluentes, alimentos e outros processos.' } },
  tags: { denim: 'JEANS / DENIM', apparel: 'CONFECÇÃO', fabric: 'TECIDO', laundries: 'LAVANDERIAS', water: 'ÁGUA / EFLUENTES', industrial: 'PROCESSOS INDUSTRIAIS' },
  products: { label: '<span>03</span> EQUIPAMENTOS', kicker: '', title: 'Máquinas para a<br /><em>operação.</em>', lead: '', laserAlt: 'Máquina laser industrial para jeans e tecidos', ozoneAlt: 'Gerador de ozônio Ozoclean em ambiente industrial', laser: { kicker: 'Texlaser · acabamento têxtil', title: 'Precisão para<br /><em>criar escala.</em>', copy: 'Laser CO₂ para jeans, camisetas e tecidos, com mais consistência no acabamento.', note: 'Dados preliminares · confirmar configuração comercial.' }, ozone: { kicker: 'Ozoclean · tratamento industrial', title: 'Processos mais<br /><em>limpos e controlados.</em>', copy: 'Geradores de ozônio para lavanderias e tratamentos industriais com mais controle.', note: 'Especificações e escopo conforme o projeto.' } },
  specs: { power: 'Potência', workArea: 'Área de trabalho', dimensions: 'Dimensões', cooling: 'Refrigeração', waterChiller: 'Água · chiller', applications: 'Aplicações', industrialLaundries: 'Lavanderias industriais', processes: 'Processos', waterWaste: 'Água e efluentes', installation: 'Instalação', projectByApplication: 'Projeto por aplicação', service: 'Atendimento', saoPaulo: 'Brasil · São Paulo' },
  applications: { label: '<span>04</span> ONDE APLICAMOS', title: 'Da lavanderia<br />à linha de produção.', copy: 'Uma base tecnológica que acompanha a necessidade do seu processo — hoje e na próxima etapa.', item1: 'Lavanderias industriais de jeans', item2: 'Confecções e beneficiamento têxtil', item3: 'Tratamento de água e efluentes', item4: 'Outras aplicações industriais' },
  process: { label: '<span>05</span> COMO TRABALHAMOS', title: 'Equipamento é o começo.<br /><span>Resultado é o objetivo.</span>', step1: { title: 'Entender', copy: 'Conversamos sobre o seu processo, volume e desafio.' }, step2: { title: 'Especificar', copy: 'Encontramos a configuração que faz sentido para a operação.' }, step3: { title: 'Implantar', copy: 'Apoiamos a entrada da tecnologia na rotina da fábrica.' }, step4: { title: 'Acompanhar', copy: 'Treinamento e suporte para manter a produção evoluindo.' } },
  contact: { label: '<span>07</span> VAMOS CONVERSAR', title: 'O próximo passo começa com uma <em>boa conversa.</em>', copy: 'Conte um pouco sobre a sua operação. Nosso atendente direciona você para a melhor solução.' },
  form: { name: 'Seu nome', namePlaceholder: 'Como podemos chamar você?', company: 'Empresa', companyPlaceholder: 'Nome da empresa', message: 'Como podemos ajudar?', messagePlaceholder: 'Fale brevemente sobre sua operação', note: 'Canal comercial oficial em configuração.', success: 'Mensagem registrada nesta demonstração.' },
  footer: { tagline: 'Precisão para o processo.<br />Presença para o resultado.', copyright: '© 2026 Texlaser Group', location: 'Atendimento próprio em São Paulo · Brasil', status: 'Site em desenvolvimento' }
};
window.TEXLASER_LOCALES['pt-BR'].language.select = 'Selecionar idioma';
window.TEXLASER_LOCALES['pt-BR'].company.tag = 'TX / 01 — BRASIL';
window.TEXLASER_LOCALES['pt-BR'].founder.markets = 'Experiência no Brasil e no exterior.';
window.TEXLASER_LOCALES['pt-BR'].products.laserStage = 'TEXLASER / CO₂';
window.TEXLASER_LOCALES['pt-BR'].products.ozoneStage = 'OZOCLEAN / O₃';
