window.TEXLASER_LOCALES = window.TEXLASER_LOCALES || {};
window.TEXLASER_LOCALES['pt-BR'] = {
  meta: { title: 'Texlaser Group — tecnologia industrial aplicada ao resultado', description: 'Texlaser Group — soluções industriais em tecnologia laser e ozônio para processos mais precisos e eficientes.' },
  brand: { home: 'Texlaser Group — início' }, nav: { menu: 'Menu', label: 'Navegação principal', solutions: 'Soluções', machines: 'Máquinas', applications: 'Aplicações', process: 'Como trabalhamos', founder: 'Fundador', company: 'Empresa' }, language: { label: 'Idioma' }, common: { talkToUs: 'Falar com um atendente <span>↗</span>', scroll: 'SCROLL <span></span>' },
  hero: { imageAlt: 'Máquina laser industrial em ambiente de produção', eyebrow: '<span class="eyebrow-line"></span> TEXLASER GROUP · BRASIL / SP', title: 'Tecnologia industrial<br /><em>para produzir melhor.</em>', copy: 'Distribuímos máquinas laser e geradores de ozônio para transformar processos industriais em mais controle, produtividade e resultado.', explore: 'Ver as máquinas <span>↓</span>', laserLabel: 'Laser têxtil', laserDetail: 'Acabamento e personalização', ozoneLabel: 'Geradores de ozônio', ozoneDetail: 'Tratamento industrial' },
  machineFocus: { label: 'MÁQUINAS / DESTAQUE', title: 'Escolha a tecnologia que entra no seu <em>processo.</em>', lead: 'Laser e ozônio para operações industriais que precisam evoluir.', laserLabel: 'TEXLASER', laserTitle: 'Laser CO₂', laserCopy: 'Acabamento, marcação e personalização têxtil.', ozoneLabel: 'OZOCLEAN', ozoneTitle: 'Geradores de ozônio', ozoneCopy: 'Tratamento industrial com mais controle.' },
  company: { label: '<span>01</span> O GRUPO', kicker: 'Duas tecnologias. Uma visão de processo.', title: 'Engenharia aplicada para quem precisa <span>produzir melhor.</span>', copy: 'A Texlaser Group distribui tecnologia industrial para empresas que não podem parar. Unimos soluções laser e ozônio a uma visão prática de operação, implantação e resultado.', cta: 'Converse com a nossa equipe <span>↗</span>', aside: 'Atendimento próprio em São Paulo, com foco em aplicações reais e relações de longo prazo.', visualCaption: 'OZOCLEAN / O₃' },
  founder: { imageAlt: 'Alex Rodrigues, fundador da Texlaser Group', caption: 'ALEX RODRIGUES · FUNDADOR', label: '<span>06</span> QUEM ESTÁ À FRENTE', kicker: 'Experiência que conhece a operação por dentro.', title: 'Alex conhece a <span>produção por dentro.</span>', copy1: 'Mais de 20 anos no laser industrial, com experiência em treinamentos, feiras e uma lavanderia de jeans.', copy2: 'Além de participar de feiras e capacitações do setor, já esteve à frente de uma lavanderia industrial para jeans.', route: 'TRAJETÓRIA PROFISSIONAL', markets: 'Brasil · Argentina · Espanha', routeDetail: 'Do Nordeste ao Sul do Brasil, com experiências também fora do país.' },
  solutions: { label: '<span>02</span> NOSSAS FRENTES', lead: 'Tecnologia certa para o processo certo. Começamos pelo universo do jeans e das lavanderias industriais.', laser: { type: 'MÁQUINAS LASER', copy: 'Acabamento, marcação e personalização com mais controle, repetibilidade e liberdade criativa para jeans, camisetas e tecidos.' }, ozone: { type: 'GERADORES DE OZÔNIO', copy: 'Geradores de ozônio para aplicações industriais em lavanderias, tratamento de água e efluentes, alimentos e outros processos.' } },
  tags: { denim: 'JEANS / DENIM', apparel: 'CONFECÇÃO', fabric: 'TECIDO', laundries: 'LAVANDERIAS', water: 'ÁGUA / EFLUENTES', industrial: 'PROCESSOS INDUSTRIAIS' },
  products: { label: '<span>03</span> EQUIPAMENTOS', kicker: 'Uma apresentação por dentro do processo', title: 'Máquinas que entram<br /><em>na operação.</em>', lead: 'Explore cada solução e seus dados técnicos.', laserAlt: 'Máquina laser industrial para jeans e tecidos', ozoneAlt: 'Gerador de ozônio Ozoclean em ambiente industrial', laser: { kicker: 'Texlaser · acabamento têxtil', title: 'Precisão para<br /><em>criar escala.</em>', copy: 'Laser CO₂ para jeans, camisetas e tecidos, com mais consistência no acabamento.', note: 'Dados preliminares · confirmar configuração comercial.' }, ozone: { kicker: 'Ozoclean · tratamento industrial', title: 'Processos mais<br /><em>limpos e controlados.</em>', copy: 'Geradores de ozônio para lavanderias e tratamentos industriais com mais controle.', note: 'Especificações e escopo conforme o projeto.' } },
  specs: { power: 'Potência', workArea: 'Área de trabalho', dimensions: 'Dimensões', cooling: 'Refrigeração', waterChiller: 'Água · chiller', applications: 'Aplicações', industrialLaundries: 'Lavanderias industriais', processes: 'Processos', waterWaste: 'Água e efluentes', installation: 'Instalação', projectByApplication: 'Projeto por aplicação', service: 'Atendimento', saoPaulo: 'Brasil · São Paulo' },
  applications: { label: '<span>04</span> ONDE APLICAMOS', title: 'Da lavanderia<br />à linha de produção.', copy: 'Uma base tecnológica que acompanha a necessidade do seu processo — hoje e na próxima etapa.', item1: 'Lavanderias industriais de jeans', item2: 'Confecções e beneficiamento têxtil', item3: 'Tratamento de água e efluentes', item4: 'Outras aplicações industriais' },
  process: { label: '<span>05</span> COMO TRABALHAMOS', title: 'Equipamento é o começo.<br /><span>Resultado é o objetivo.</span>', step1: { title: 'Entender', copy: 'Conversamos sobre o seu processo, volume e desafio.' }, step2: { title: 'Especificar', copy: 'Encontramos a configuração que faz sentido para a operação.' }, step3: { title: 'Implantar', copy: 'Apoiamos a entrada da tecnologia na rotina da fábrica.' }, step4: { title: 'Acompanhar', copy: 'Treinamento e suporte para manter a produção evoluindo.' } },
  contact: { label: '<span>07</span> VAMOS CONVERSAR', title: 'O próximo passo começa com uma <em>boa conversa.</em>', copy: 'Conte um pouco sobre a sua operação. Nosso atendente direciona você para a melhor solução.' },
  form: { name: 'Seu nome', namePlaceholder: 'Como podemos chamar você?', company: 'Empresa', companyPlaceholder: 'Nome da empresa', message: 'Como podemos ajudar?', messagePlaceholder: 'Fale brevemente sobre sua operação', note: 'Canal comercial oficial em configuração.', success: 'Mensagem registrada nesta demonstração.' },
  footer: { tagline: 'Precisão para o processo.<br />Presença para o resultado.', copyright: '© 2026 Texlaser Group', location: 'Atendimento próprio em São Paulo · Brasil', status: 'Site em desenvolvimento' }
};
window.TEXLASER_LOCALES['pt-BR'].language.select = 'Selecionar idioma';
window.TEXLASER_LOCALES['pt-BR'].company.tag = 'TX / 01 — BRASIL';
window.TEXLASER_LOCALES['pt-BR'].founder.markets = 'Brasil · Argentina · Espanha';
window.TEXLASER_LOCALES['pt-BR'].products.laserStage = 'TEXLASER / CO₂';
window.TEXLASER_LOCALES['pt-BR'].products.ozoneStage = 'OZOCLEAN / O₃';
